### ISSUE TITLE
How do I disable logging of checking providers records?

### ISSUE THREAD

**Issue by LordMerlin** [DeNetPRO/Node#5]
In the new version, the node began to log the process of checking providers.
For example, and beyond
checking 1 of 32 providers from queue 
checking 2 of 32 providers from queue 
checking 3 of 32 providers from queue 
checking 4 of 32 providers from queue 
checking 5 of 32 providers from queue 
checking 6 of 32 providers from queue 
............................

Is it possible to somehow reduce the amount issued to the log? It grows a few days to a size of hundreds of megabytes. I don't want to turn off logging at all. It is necessary to somehow follow the process.

**Comment by cyb3rKn1ght** [comment]
Can't do it right now, will disable it in the nearest release
